
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimetableCreationTool
{

using System;
    using System.Collections.Generic;
    
public partial class Lecturer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Lecturer()
    {

        this.Timetables = new HashSet<Timetable>();

        this.Modules = new HashSet<Module>();

    }


    public int lecturerId { get; set; }

    public string lecturerName { get; set; }

    public string lecturerDept { get; set; }

    public string lecturerCode { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Timetable> Timetables { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Module> Modules { get; set; }

}

}
