
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TimetableCreationTool
{

using System;
    using System.Collections.Generic;
    
public partial class roomTemp
{

    public string roomCode { get; set; }

    public int capacity { get; set; }

    public bool lab { get; set; }

}

}
